# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tgbot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='یوزرنیم تلگرام')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], null=True, verbose_name='جنسیت')),
                ('age', models.IntegerField(blank=True, choices=[(1, 'زیر ۱۰'), (2, '۱۰-۲۰'), (3, '۲۰-۳۰'), (4, '۳۰-۴۰'), (5, '۴۰-۵۰'), (6, '۵۰-۶۰'), (7, 'بالای ۶۰')], null=True, verbose_name='سن')),
                ('sentence_is_reading', models.IntegerField(blank=True, null=True, verbose_name='کد جمله\u200cای که می\u200cخواهد بخواند')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'افراد',
                'verbose_name': 'فرد',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_file_id', models.URLField(blank=True, null=True, verbose_name='شناسه\u200cی فایل در تلگرام')),
                ('voice_url', models.URLField(blank=True, null=True, verbose_name='آدرس قابل دانلود')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'پیش\u200cفرض'), (2, 'مورد تایید')], default=1, null=True, verbose_name='وضعیت ثبت')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان فایل')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='انرژی سیگنال')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tgbot.People', verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'رکوردها',
                'verbose_name': 'رکورد',
                'ordering': ('-creation_time',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='متن ارسال شده')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد متن')),
                ('sample_voice', models.FileField(blank=True, null=True, upload_to=tgbot.models.Text._get_upload_path, verbose_name='صدای نمونه')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name_plural': 'متن\u200cها',
                'verbose_name': 'متن',
                'ordering': ('-creation_time',),
            },
        ),
        migrations.AddField(
            model_name='record',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tgbot.Text', verbose_name='متن ارسال شده'),
        ),
    ]
