# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='phonetic',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='آوانویسی'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=700, verbose_name='متن ارسال شده'),
        ),
    ]
