# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tgbot.People', verbose_name='بازیکن'),
        ),
        migrations.AlterField(
            model_name='score',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tgbot.Record', verbose_name='رکورد'),
        ),
    ]
