# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20170126_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, 'ژێر ١٠ ساڵ'), (2, '١٠-٢٠'), (3, '٢٠-٣٠'), (4, '٣٠-٤٠'), (5, '٤٠-٥٠'), (6, '٥٠-٦٠'), (7, 'زیاتر لە ٦٠ ساڵ')], null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='people',
            name='sentence_is_reading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد جمله\u200cای که می\u200cخواهد بخواند'),
        ),
    ]
